services:
  postgres:
    image: postgres:14
    container_name: postgres14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails-lab
    ports:
      - "5432:5432"
    volumes:
      - postgres14_data:/var/lib/postgresql/data

volumes:
  postgres14_data:
